-- Inserts soft hyphens (U+00AD) into long Swedish words in
-- public.questions.options_json, based on the 324-word mapping below
-- (sourced from scripts/hyphenation/proposals.csv).
--
-- Idempotent: the discovery query that produced the mapping treats existing
-- soft hyphens as word boundaries, so already-hyphenated words don't appear
-- here. Running this twice is a no-op on the second pass.
--
-- Substring behaviour is intentional: matching by `LIKE '%word%'` (sorted by
-- word length DESC) also catches inflected forms not in the mapping. E.g.
-- if 'Hundraårskrigets' appears in the DB but isn't listed below, it still
-- gets hyphenated correctly via the 'Hundraårskriget' rule.
--
-- Note: the Supabase SQL editor auto-commits each run, so this script does
-- not wrap the UPDATE in BEGIN/COMMIT. To preview safely, run in psql or a
-- desktop client that supports manual transaction control.

WITH RECURSIVE word_map(long_word, hyphenated) AS (
	VALUES
		('adrenalininjektion'::text, 'adre­nalin­injek­tion'::text),
		('afroamerikanska', 'afro­ameri­kanska'),
		('Aktiebolagslagen', 'Aktie­bolags­lagen'),
		('alkoholiserad', 'alko­holi­serad'),
		('Änkegrevinnan', 'Änke­grevinnan'),
		('Artemistemplet', 'Artemis­templet'),
		('bakelsekriget', 'bakelse­kriget'),
		('barnbarnsbarn', 'barn­barns­barn'),
		('Bärnstenskikaren', 'Bärnstens­kikaren'),
		('Bartolomeinatten', 'Bartolomei­natten'),
		('begravningsfirma', 'begravnings­firma'),
		('Bergsmansgårdens', 'Bergsmans­gårdens'),
		('Blåbärsyoghurt', 'Blåbärs­yoghurt'),
		('Blindtestmannen', 'Blind­test­mannen'),
		('Bosnienkriget', 'Bosnien­kriget'),
		('bostadsöverskott', 'bostads­överskott'),
		('bostadsskattereformen', 'bostads­skatte­reformen'),
		('Brachiosaurus', 'Brachio­saurus'),
		('Brandenburgkonserterna', 'Brandenburg­konser­terna'),
		('brednoskajman', 'bred­nos­kajman'),
		('Bridgewaterkanalen', 'Bridge­water­kanalen'),
		('brigadgeneral', 'brigad­general'),
		('Bröllopsfotografen', 'Bröllops­fotografen'),
		('bröllopsklänning', 'bröllops­klänning'),
		('Californication', 'Cali­forni­cation'),
		('Canossavandring', 'Canossa­vandring'),
		('cementblandaren', 'cement­blandaren'),
		('Centerpartiet', 'Center­partiet'),
		('Cheopspyramiden', 'Cheops­pyramiden'),
		('Choladynastins', 'Chola­dynastins'),
		('cirkusstjärna', 'cirkus­stjärna'),
		('Columbinemassakern', 'Columbine­massakern'),
		('Correspondenten', 'Corre­sponden­ten'),
		('crushcrushcrush', 'crush­crush­crush'),
		('Cryolophosaurus', 'Cryolopho­saurus'),
		('Darfurkonflikten', 'Darfur­konflikten'),
		('Daytonavtalet', 'Dayton­avtalet'),
		('defibrillator', 'defi­brilla­tor'),
		('departementschefer', 'departements­chefer'),
		('diskoteksbranden', 'diskoteks­branden'),
		('Diskrimineringslagen', 'Diskri­minerings­lagen'),
		('Dödsrelikerna', 'Döds­relikerna'),
		('Drömfakulteten', 'Dröm­fakulteten'),
		('dubbelkvartett', 'dubbel­kvartett'),
		('Dubrovkateatern', 'Dubrovka­teatern'),
		('Ekvatorialguinea', 'Ekvatorial­guinea'),
		('Elfenbenskusten', 'Elfenbens­kusten'),
		('enhjärtbladiga', 'en­hjärt­bladiga'),
		('Eriksdalsbadet', 'Eriksdals­badet'),
		('Estoniakatastrofen', 'Estonia­katastrofen'),
		('Evolutionsteorin', 'Evolutions­teorin'),
		('Fackförbundet', 'Fack­förbundet'),
		('Fågelfångarens', 'Fågel­fångarens'),
		('Falklandskriget', 'Falklands­kriget'),
		('familjemedlem', 'familje­medlem'),
		('fängelseritning', 'fängelse­ritning'),
		('fildelningslagen', 'fildelnings­lagen'),
		('finansminister', 'finans­minister'),
		('fjällgentiana', 'fjäll­gentiana'),
		('fjärdedelsnot', 'fjärdedels­not'),
		('flanellskjortor', 'flanell­skjortor'),
		('flygkraschöverlevande', 'flyg­krasch­överlevande'),
		('folkomröstning', 'folk­omröstning'),
		('fönsterkarmarna', 'fönster­karmarna'),
		('Föräldrabalken', 'Föräldra­balken'),
		('förbundsländer', 'förbunds­länder'),
		('Förbundsrepubliken', 'Förbunds­republiken'),
		('författningar', 'för­fattningar'),
		('förskräcklige', 'för­skräcklige'),
		('fotbollskriget', 'fotbolls­kriget'),
		('Fredericksburg', 'Frede­ricks­burg'),
		('Frihetsgudinnan', 'Frihets­gudinnan'),
		('frihetskriget', 'frihets­kriget'),
		('fripassagerare', 'fri­passagerare'),
		('Friskolereformen', 'Friskole­reformen'),
		('Frühlingserwachen', 'Frühlings­erwachen'),
		('Genèvekonventionen', 'Genève­konven­tionen'),
		('Giganotosaurus', 'Giganoto­saurus'),
		('gisslandramat', 'gisslan­dramat'),
		('Glasögonsmurf', 'Glasögon­smurf'),
		('globaliseringen', 'globali­seringen'),
		('Göteborgskravallerna', 'Göteborgs­kraval­lerna'),
		('grannkonflikter', 'grann­konflikter'),
		('Grisbuktsinvasionen', 'Grisbukts­inva­sionen'),
		('grönsaksodlare', 'grönsaks­odlare'),
		('Halikarnassos', 'Hali­karnassos'),
		('hälsotidningar', 'hälso­tidningar'),
		('Halvblodsprinsen', 'Halvblods­prinsen'),
		('handelsresandes', 'handels­resandes'),
		('Heksanosaurus', 'Heksano­saurus'),
		('Hjärnkontoret', 'Hjärn­kontoret'),
		('hjärttransplantationen', 'hjärt­transplan­tationen'),
		('honungsvisare', 'honungs­visare'),
		('hotellmagnatens', 'hotell­magnatens'),
		('hundraårskriget', 'hundra­års­kriget'),
		('Hundraårskriget', 'Hundra­års­kriget'),
		('hushållspapper', 'hushålls­papper'),
		('huvudfigurerna', 'huvud­figurerna'),
		('huvudpersonen', 'huvud­personen'),
		('huvudpersonens', 'huvud­personens'),
		('impressionism', 'impres­sionism'),
		('inbördeskriget', 'inbördes­kriget'),
		('indelningsverkets', 'indelnings­verkets'),
		('individualism', 'indi­vidu­alism'),
		('Indokinakriget', 'Indokina­kriget'),
		('inkvisitionen', 'inkvi­sitionen'),
		('inlandstaipan', 'inlands­taipan'),
		('inspelningshuset', 'inspelnings­huset'),
		('inspelningsländer', 'inspelnings­länder'),
		('International', 'Inter­national'),
		('Investigation', 'Investi­gation'),
		('jakobitupproret', 'jakobit­upproret'),
		('jordbävningen', 'jord­bävningen'),
		('jordnötsodlare', 'jordnöts­odlare'),
		('julbombningarna', 'jul­bombningarna'),
		('Kalmarunionen', 'Kalmar­unionen'),
		('Kameraövervakningslagen', 'Kamera­övervaknings­lagen'),
		('Kangchenjunga', 'Kang­chen­junga'),
		('Kankbergsgruvan', 'Kankbergs­gruvan'),
		('kannibalistisk', 'kanni­balistisk'),
		('Karamelodiktstipendiet', 'Karamelodikt­stipendiet'),
		('kardinaltetra', 'kardinal­tetra'),
		('kataraktoperation', 'katarakt­opera­tion'),
		('koalitionskriget', 'koalitions­kriget'),
		('kolecystektomi', 'kole­cyst­ektomi'),
		('koleraepidemi', 'kolera­epidemi'),
		('komplementfärg', 'komplement­färg'),
		('konsumentfrågor', 'konsument­frågor'),
		('kontrollpunkt', 'kontroll­punkt'),
		('kortikosteroider', 'kortiko­steroider'),
		('Kosovokonflikten', 'Kosovo­konflikten'),
		('kreditförluster', 'kredit­förluster'),
		('krigsförklaring', 'krigs­förklaring'),
		('Kristdemokraterna', 'Krist­demokraterna'),
		('kronprinsessan', 'kron­prinsessan'),
		('Kronprinsessan', 'Kron­prinsessan'),
		('kroppstemperaturen', 'kropps­tempera­turen'),
		('Kungsträdgården', 'Kungs­trädgården'),
		('kvicksilverånga', 'kvick­silver­ånga'),
		('kvicksilverbarometer', 'kvick­silver­baro­meter'),
		('kyrktornsprincipen', 'kyrk­torns­principen'),
		('Kyroskrönikan', 'Kyros­krönikan'),
		('Landstigningen', 'Land­stigningen'),
		('landsvägscykling', 'landsvägs­cykling'),
		('längdskidåkning', 'längd­skid­åkning'),
		('Lärarförbundet', 'Lärar­förbundet'),
		('Liechtenstein', 'Liech­ten­stein'),
		('ljudhastigheten', 'ljud­hastigheten'),
		('magnesiumsulfat', 'magnesium­sulfat'),
		('människohuvud', 'människo­huvud'),
		('manusförfattarens', 'manus­författarens'),
		('marginalränta', 'marginal­ränta'),
		('Marianergraven', 'Marianer­graven'),
		('Marshallöarna', 'Marshall­öarna'),
		('Marshallplanen', 'Marshall­planen'),
		('Maskeradligan', 'Maskerad­ligan'),
		('Massachusetts', 'Massa­chusetts'),
		('metatarsalben', 'metatarsal­ben'),
		('Midvinterblot', 'Mid­vinter­blot'),
		('militärrådgivare', 'militär­rådgivare'),
		('miljörörelsen', 'miljö­rörelsen'),
		('ministerrådet', 'minister­rådet'),
		('Mississippifloden', 'Mississippi­floden'),
		('mjältbrandsattackerna', 'mjältbrands­attack­erna'),
		('möbelkollektionen', 'möbel­kollek­tionen'),
		('Monopolspelet', 'Monopol­spelet'),
		('mordrättegång', 'mord­rättegång'),
		('morsealfabetet', 'morse­alfabetet'),
		('Muhammedkarikatyrerna', 'Muhammed­karika­tyrerna'),
		('musiktalangtävling', 'musik­talang­tävling'),
		('musiktopplista', 'musik­topp­lista'),
		('Näckrosdammen', 'Näckros­dammen'),
		('nationaliserar', 'nationa­liserar'),
		('nationalmuseum', 'national­museum'),
		('Nationalteatern', 'National­teatern'),
		('Nederländerna', 'Neder­länderna'),
		('nervgasattacken', 'nervgas­attacken'),
		('Niagarafallen', 'Niagara­fallen'),
		('Nobelpriserna', 'Nobel­priserna'),
		('Nordvästpassagen', 'Nord­väst­passagen'),
		('nyhetsprogram', 'nyhets­program'),
		('nyutexaminerad', 'ny­utexa­minerad'),
		('offentliggörs', 'offentlig­görs'),
		('Oklahomabombaren', 'Oklahoma­bombaren'),
		('Oktoberfolket', 'Oktober­folket'),
		('omslagsbilder', 'omslags­bilder'),
		('oövervinnliga', 'o­över­vinnliga'),
		('Öresundsförbindelsen', 'Öresunds­förbind­elsen'),
		('Orientexpressen', 'Orient­expressen'),
		('ormbunksväxter', 'ormbunks­växter'),
		('överbeskyddande', 'över­beskyddande'),
		('Overprotected', 'Over­protected'),
		('påfågelciklid', 'påfågel­ciklid'),
		('paniksparande', 'panik­sparande'),
		('pansaranfallet', 'pansar­anfallet'),
		('pappersklämma', 'pappers­klämma'),
		('parfymföretag', 'parfym­företag'),
		('Parisfördraget', 'Paris­fördraget'),
		('Parisupploppen', 'Paris­upploppen'),
		('passionsfrukt', 'passions­frukt'),
		('Paulskatedralen', 'Pauls­katedralen'),
		('Pelikanfallet', 'Pelikan­fallet'),
		('Peloponnesiska', 'Pelo­ponne­siska'),
		('personifieringen', 'personi­fieringen'),
		('polaroidbilder', 'polaroid­bilder'),
		('Politkovskaja', 'Polit­kovskaja'),
		('Portsmouthfördraget', 'Portsmouth­fördraget'),
		('postmodernism', 'post­modernism'),
		('Potalapalatset', 'Potala­palatset'),
		('Powerpuffpinglorna', 'Powerpuff­pinglorna'),
		('premiärminister', 'premiär­minister'),
		('presidentperiod', 'president­period'),
		('Produktionsbolag', 'Produktions­bolag'),
		('produktionsbolaget', 'produktions­bolaget'),
		('produkttester', 'produkt­tester'),
		('programledare', 'program­ledare'),
		('programledaren', 'program­ledaren'),
		('radioaktivitet', 'radio­aktivitet'),
		('ränteavdragsrätten', 'ränte­avdrags­rätten'),
		('rättigheterna', 'rättig­heterna'),
		('rättvisemärke', 'rättvise­märke'),
		('realitystjärna', 'reality­stjärna'),
		('reformationen', 'refor­mationen'),
		('Regeringsformen', 'Regerings­formen'),
		('regnbågsflaggan', 'regnbågs­flaggan'),
		('Religionfrihetslagen', 'Religion­frihets­lagen'),
		('Riksdagsordningen', 'Riksdags­ordningen'),
		('rollercoaster', 'roller­coaster'),
		('rombkuboktaeder', 'romb­kub­oktaeder'),
		('rullstolsburen', 'rullstols­buren'),
		('Rwandakommission', 'Rwanda­kommission'),
		('Sakellaropoulou', 'Sakella­ropoulou'),
		('Sällskapsresan', 'Sällskaps­resan'),
		('Sammansvärjningen', 'Samman­svärjningen'),
		('sändningsdatum', 'sändnings­datum'),
		('schackmästaren', 'schack­mästaren'),
		('Schwarzenegger', 'Schwar­zenegger'),
		('Scovilleskalan', 'Scoville­skalan'),
		('septemberrörelsen', 'september­rörelsen'),
		('sexdagarskriget', 'sexdagars­kriget'),
		('Silariusfloden', 'Silarius­floden'),
		('silverstjärna', 'silver­stjärna'),
		('siminstruktör', 'sim­instruktör'),
		('självförvaltning', 'själv­förvaltning'),
		('självständigheten', 'själv­ständig­heten'),
		('självständighetskriget', 'själv­ständighets­kriget'),
		('självständigt', 'själv­ständigt'),
		('sjöflygplanet', 'sjö­flygplanet'),
		('sjöförbundets', 'sjö­förbundets'),
		('sjukgymnasten', 'sjuk­gymnasten'),
		('Skagerrakslaget', 'Skagerraks­laget'),
		('skaldjursutomjordingsläkare', 'skaldjurs­utom­jordings­läkare'),
		('skandinaviska', 'skandi­naviska'),
		('skandinavismen', 'skandi­navismen'),
		('Skärgårdsdoktorn', 'Skärgårds­doktorn'),
		('skönhetsfläck', 'skönhets­fläck'),
		('Smålandsposten', 'Smålands­posten'),
		('socialbidragsberoendet', 'social­bidrags­beroendet'),
		('Socialdemokraterna', 'Social­demokraterna'),
		('solobestigning', 'solo­bestigning'),
		('Sovjetunionen', 'Sovjet­unionen'),
		('Spindelmannen', 'Spindel­mannen'),
		('sportinriktning', 'sport­inriktning'),
		('sprintlöpning', 'sprint­löpning'),
		('statsbankrutt', 'stats­bankrutt'),
		('statskuppsförsöket', 'statskupps­försöket'),
		('statsminister', 'stats­minister'),
		('statsministern', 'stats­ministern'),
		('stilleståndsavtal', 'stillestånds­avtal'),
		('Stockstötning', 'Stock­stötning'),
		('Storbritannien', 'Stor­britannien'),
		('stuprörspolitik', 'stuprörs­politik'),
		('Successionsordningen', 'Succes­sions­ordningen'),
		('superdevalvering', 'super­devalvering'),
		('superintelligent', 'super­intelligent'),
		('Supernaturals', 'Super­naturals'),
		('svenskspråkiga', 'svensk­språkiga'),
		('Sverigedemokraterna', 'Sverige­demokraterna'),
		('Svinalängorna', 'Svina­längorna'),
		('taggutskottet', 'tagg­utskottet'),
		('terroristattackerna', 'terrorist­attack­erna'),
		('Tetoffensiven', 'Tet­offensiven'),
		('tillväxthormon', 'tillväxt­hormon'),
		('Tjeckoslovakien', 'Tjecko­slovakien'),
		('Tjetjenienkriget', 'Tjetjenien­kriget'),
		('tobakshandlaren', 'tobaks­handlaren'),
		('Tonkinbuktintermezzot', 'Tonkin­bukt­intermezzot'),
		('Torekovskompromissen', 'Torekovs­kompromissen'),
		('torgmassakern', 'torg­massakern'),
		('trädgårdstomte', 'trädgårds­tomte'),
		('Trainspotting', 'Train­spotting'),
		('Transnistrien', 'Trans­nistrien'),
		('Trettondagsafton', 'Trettondags­afton'),
		('trikuspidalis', 'triku­spidalis'),
		('tronföljdskriget', 'tronföljds­kriget'),
		('truckerkepsen', 'trucker­kepsen'),
		('tvåhjärtbladiga', 'två­hjärt­bladiga'),
		('tvångssparandet', 'tvångs­sparandet'),
		('Tyrannosaurus', 'Tyranno­saurus'),
		('underklädslinning', 'under­kläds­linning'),
		('Undervattenshockey', 'Under­vattens­hockey'),
		('undervattensrugby', 'under­vattens­rugby'),
		('universitetet', 'univer­sitetet'),
		('Uppsalamaffian', 'Uppsala­maffian'),
		('Vänsterpartiet', 'Vänster­partiet'),
		('vänstertrafik', 'vänster­trafik'),
		('världskrigets', 'världs­krigets'),
		('världsmästare', 'världs­mästare'),
		('världsomseglingen', 'världs­omseglingen'),
		('varmluftsballong', 'varmlufts­ballong'),
		('Vasilijkatedralen', 'Vasilij­katedralen'),
		('Vatikanmuseerna', 'Vatikan­museerna'),
		('Vatikanstaten', 'Vatikan­staten'),
		('Vattenfestivalen', 'Vatten­festivalen'),
		('Vattenmelonen', 'Vatten­melonen'),
		('vattenstämpel', 'vatten­stämpel'),
		('Versaillesfreden', 'Versailles­freden'),
		('Victoriafallen', 'Victoria­fallen'),
		('Vietnamkriget', 'Vietnam­kriget'),
		('vinterlandskap', 'vinter­landskap'),
		('Warszawapakten', 'Warszawa­pakten'),
		('Watergateskandalen', 'Watergate­skandalen'),
		('Yttrandefrihetsgrundlagen', 'Yttrande­frihets­grund­lagen'),
		('zombiegorillorna', 'zombie­gorillorna')
),
expanded AS (
	SELECT
		q.id AS question_id,
		(t.idx - 1) AS option_index,
		t.elem #>> '{}' AS option_text
	FROM public.questions q
	CROSS JOIN LATERAL
		jsonb_array_elements(q.options_json) WITH ORDINALITY AS t(elem, idx)
	WHERE q.archived_at IS NULL
		AND jsonb_typeof(t.elem) = 'string'
),
matches AS (
	SELECT
		e.question_id,
		e.option_index,
		e.option_text,
		array_agg(w.long_word ORDER BY length(w.long_word) DESC, w.long_word) AS find_words,
		array_agg(w.hyphenated ORDER BY length(w.long_word) DESC, w.long_word) AS replace_words
	FROM expanded e
	JOIN word_map w ON e.option_text LIKE '%' || w.long_word || '%'
	GROUP BY e.question_id, e.option_index, e.option_text
),
applied AS (
	SELECT
		question_id,
		option_index,
		option_text AS current_text,
		find_words,
		replace_words,
		0 AS step
	FROM matches
	UNION ALL
	SELECT
		question_id,
		option_index,
		replace(current_text, find_words[step + 1], replace_words[step + 1]),
		find_words,
		replace_words,
		step + 1
	FROM applied
	WHERE step < array_length(find_words, 1)
),
final AS (
	SELECT DISTINCT ON (question_id, option_index)
		question_id,
		option_index,
		current_text AS new_text
	FROM applied
	ORDER BY question_id, option_index, step DESC
)
-- Rebuild the entire options_json per affected question. This avoids the
-- `UPDATE … FROM` quirk where multiple source rows joining the same target
-- row collapse to a single update (which would only hyphenate one slot per
-- question, even when several slots needed it).
,per_question AS (
	SELECT
		question_id,
		jsonb_object_agg(option_index::text, to_jsonb(new_text)) AS edits
	FROM final
	GROUP BY question_id
)
UPDATE public.questions q
SET options_json = (
	SELECT jsonb_agg(
		coalesce(p.edits -> ((t.ord - 1)::text), t.elem)
		ORDER BY t.ord
	)
	FROM jsonb_array_elements(q.options_json) WITH ORDINALITY AS t(elem, ord)
)
FROM per_question p
WHERE q.id = p.question_id;

-- Sanity check: number of option-slots that now contain a soft hyphen.
-- Should be substantially higher than 208 (the previous run only hyphenated
-- one slot per question due to the now-fixed UPDATE … FROM quirk).
SELECT count(*) AS hyphenated_slots
FROM public.questions q
CROSS JOIN LATERAL
	jsonb_array_elements(q.options_json) AS t(elem)
WHERE q.archived_at IS NULL
	AND jsonb_typeof(t.elem) = 'string'
	AND (t.elem #>> '{}') LIKE '%' || chr(173) || '%';
